### ISSUE TITLE
cannot train with mutil gpus

### ISSUE THREAD

**Issue by smiler96** [aiff22/PyNET#10]
hello, does this can be trainned on mutil gpus?
when i train these code with two gpus, while just exe on one gpu.
not familiar with tf, could you please give some guidence how to trainning on mutil gpus with your code? thanks.

**Comment by aiff22** [comment]
Please check [these instructions](https://www.tensorflow.org/guide/distributed_training). If you are familiar with PyTorch - you can simply use [the corresponding model implementation](https://github.com/aiff22/PyNET-PyTorch).
