### ISSUE TITLE
EBB Dataset

### ISSUE THREAD

**Issue by nuvinga** [aiff22/PyNET#12]
Hi, Where can I find the EBB complete dataset? 

The competition site, to which I'm directed to get the test dataset at-leats to is not updated since 2020. So it does not provide the complete dataset. 

This is for a university project. Would be appreciated very much if this could be addressed ASAP.

**Comment by aiff22** [comment]
> Hi, Where can I find the EBB complete dataset?

You can download the entire training part of the dataset after registering in the competition.

**Comment by xiaofeinot** [comment]
> Hi, Where can I find the EBB complete dataset?
> 
> The competition site, to which I'm directed to get the test dataset at-leats to is not updated since 2020. So it does not provide the complete dataset.
> 
> This is for a university project. Would be appreciated very much if this could be addressed ASAP.

Hi nuvinga,  did you get EBB train dataset now? It looks that aim2020 website didn't allow new registers. If you have the dataset, could you please share me a copy? thanks very much !

**Comment by dongdk** [comment]
> > Hi, Where can I find the EBB complete dataset?
> > The competition site, to which I'm directed to get the test dataset at-leats to is not updated since 2020. So it does not provide the complete dataset.
> > This is for a university project. Would be appreciated very much if this could be addressed ASAP.
> 
> Hi nuvinga, did you get EBB train dataset now? It looks that aim2020 website didn't allow new registers. If you have the dataset, could you please share me a copy? thanks very much !

+1
