### ISSUE TITLE
level_5 module

### ISSUE THREAD

**Issue by DxqS** [aiff22/PyNET#5]
![image](https://user-images.githubusercontent.com/20105347/75842806-5c564e80-5e0c-11ea-8e41-a39d5f6bf5c7.png)

![image](https://user-images.githubusercontent.com/20105347/75842874-958ebe80-5e0c-11ea-8d9e-f630b5683e22.png)

which one is right？

**Comment by Jam-G** [comment]
@DxqS The code you shown in the second picture, is pytorch implementation of PyNET，and  the tensorflow implementation of PyNET is same to the description in papers.

And I checked the [pytorch implementation of PyNET](https://github.com/aiff22/PyNET-PyTorch) ， the autor @aiff22 modified the model exactly and declared three major  modifications.
But he  didn't mention the modifications about dropping the skip connections of level5.  
If @aiff22 have tried such modifications and it has better effects？ or just omitted?
It confused me too.

**Comment by aiff22** [comment]
Hi @DxqS, @Jam-G,

The right one is in the paper and in this repository. In the PyTorch repository, it was just omitted by mistake. You can add skip-connections in the 5th level by changing the above code to:

```bash
 def level_5(self, pool4):

        conv_l5_d1 = self.conv_l5_d1(pool4)
        conv_l5_d2 = self.conv_l5_d2(conv_l5_d1) + conv_l5_d1
        conv_l5_d3 = self.conv_l5_d3(conv_l5_d2) + conv_l5_d2
        conv_l5_d4 = self.conv_l5_d4(conv_l5_d3)

        conv_t4a = self.conv_t4a(conv_l5_d4)
        conv_t4b = self.conv_t4b(conv_l5_d4)

        conv_l5_out = self.conv_l5_out(conv_l5_d4)
        output_l5 = self.output_l5(conv_l5_out)

        return output_l5, conv_t4a, conv_t4b

```
